# Generated by Django 4.0.1 on 2022-01-15 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.UUID('07e464eb-0c9d-4b9f-a9c3-74dc7d6b37a0'), editable=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
